name: Coverage Badge

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    name: Generate Coverage Badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Calculate Go Calc Supervisor Coverage
        id: calc_coverage
        working-directory: ./go-calc-supervisor
        run: |
          go test -tags test -coverprofile=coverage.out
          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
          echo "coverage=$coverage" >> $GITHUB_OUTPUT
          echo "Calculator Supervisor Coverage: $coverage"

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: YOUR_GIST_ID_HERE  # Replace with actual Gist ID
          filename: calc-supervisor-coverage.json
          label: Coverage
          message: ${{ steps.calc_coverage.outputs.coverage }}
          color: |
            ${{
              contains(steps.calc_coverage.outputs.coverage, '9') && 'brightgreen' ||
              contains(steps.calc_coverage.outputs.coverage, '8') && 'green' ||
              contains(steps.calc_coverage.outputs.coverage, '7') && 'yellowgreen' ||
              contains(steps.calc_coverage.outputs.coverage, '6') && 'yellow' ||
              'red'
            }}